version: "3.3"  # optional since v1.27.0
services:
  eureka-server:
    build: .
    ports:
      - "7150:7150"
    container_name: service-registry
    networks:
      - imsablabla

networks:
  imsablabla: